ci: add repo workflow

diff --git a/.github/workflows/reusable-repo-issue.yml b/.github/workflows/reusable-repo-issue.yml
--- a/.github/workflows/reusable-repo-issue.yml
+++ b/.github/workflows/reusable-repo-issue.yml
@@ -1,5 +1,5 @@
 ---
-name: Reusable - Repository SAST Checks
+name: Reusable - Repository SCA Checks
 on: # yamllint disable-line rule:truthy
   workflow_call:
 
@@ -9,7 +9,7 @@ permissions:
 
 jobs:
   repo-security:
-    name: Run SAST checks
+    name: Run SCA checks
     runs-on: ubuntu-24.04
     timeout-minutes: 10
 
@@ -19,12 +19,12 @@ jobs:
         with:
           fetch-depth: 0  # Fetch all branches
 
-      - name: Check if main.yml calls SAST workflow
+      - name: Check if main.yml calls SCA workflow
         run: |
-          if ! grep -q "sast" .github/workflows/main.yml; then
-            echo "::error file=.github/workflows/main.yml::❌ main.yml does not call the SAST action (reusable-repo-sast)!"
+          if ! grep -q "sca" .github/workflows/main.yml; then
+            echo "::error file=.github/workflows/main.yml::❌ main.yml does not call the SCA action (reusable-repo-sca)!"
             exit 1
           else
-            echo "✅ main.yml calls the SAST action."
+            echo "✅ main.yml calls the SCA action."
           fi
         continue-on-error: true
